
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Jonathan_Dev
 */
public class panel_item extends javax.swing.JPanel {

    /**
     * Creates new form panel_item
     */
    private frame_main mf;

    public panel_item(int sitemid, String nameitem, double cost, String SIMG, frame_main mf) {
        this.mf = mf;

        initComponents();
        setItem(sitemid, nameitem, cost, SIMG);
    }

    int itemID;

//    public void setItem(int sitemid, String sname, double scost, String sImg) {
//
//        System.out.println("Img : " + sImg);
//
//        //ImageIcon icon = new ImageIcon("/imgs/" + sImg + ".png");
//
//        itemID = sitemid;
//        lb_name.setText(sname);
//        lb_price.setText(scost + "");
//        //lb_img.setIcon(icon);
//        
//        if (sImg == null || sImg.trim().isEmpty()) {
//            lb_img.setIcon(null);  // ถ้า sImg เป็น null หรือค่าว่าง ก็ให้ลบไอคอนใน JLabel
//        } else {
//            // โหลดภาพจาก Resource และตั้งค่าให้กับ lb_img
//            lb_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/" + sImg + ".png"))); // NOI18N
//        }
//        
//
//    }
    
    public void setItem(int sitemid, String sname, double scost, String sImg) {
        System.out.println("Img : " + sImg);

        itemID = sitemid;
        lb_name.setText(sname);
        lb_price.setText(scost + "");

        // ตรวจสอบว่า sImg เป็น null หรือค่าว่างหรือไม่
        if (sImg == null || sImg.trim().isEmpty()) {
            lb_img.setIcon(null);  // ถ้า sImg เป็น null หรือค่าว่าง ก็ให้ลบไอคอนใน JLabel
        } else {
            // ตรวจสอบว่าไฟล์ภาพสามารถโหลดได้จาก resource path หรือไม่
            java.net.URL imgUrl = getClass().getResource("/imgs/" + sImg + ".png");

            if (imgUrl != null) {
                // ถ้าภาพสามารถโหลดได้ ก็จะสร้าง ImageIcon และตั้งค่าให้กับ lb_img
                lb_img.setIcon(new javax.swing.ImageIcon(imgUrl));
            } else {
                // ถ้าไม่พบไฟล์ภาพ ให้แสดงข้อความใน console และลบไอคอนใน JLabel
                System.out.println("Image not found: /imgs/" + sImg + ".png");
                lb_img.setIcon(null);  // ลบไอคอนใน JLabel
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_img = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        lb_price = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lb_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_name.setText("ItemName");

        lb_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_price.setText("20.00 ฿");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lb_img, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lb_price)
                                .addGap(12, 12, 12))
                            .addComponent(lb_name))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb_img, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_price)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        //ArrayList<String> data = new ArrayList<>();
        
        System.out.println(lb_price.getText());
//        String data = lb_price.getText();
//        mf.updateResult(data);

        String itemN = lb_name.getText();
        double pricE = Double.valueOf(lb_price.getText());
        String des = "-";

        mf.updateTableList(itemID, itemN, pricE, des);
//        mf.updateTotalValue(pricE);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_img;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_price;
    // End of variables declaration//GEN-END:variables
}
